language: node_js
node_js:
  - "8"
cache: yarn
env:
  - SB_SERVER_ONLY=1 CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

install:
  - cd server && yarn && cd .. && yarn
