# The electron-builder config for the production site (https://shieldbattery.net)
# It should generally match the other build configs (except things that need to differ for this
# "region")
appId: net.shieldbattery.client
extraResources:
- game/dist/**
- "!game/dist/**/*.map"
files:
- "!**/*.map"
- "!build/**/*"
nsis:
  artifactName: "${productName}-setup-${version}.${ext}"
  # There's currently a bug with Windows Defender that makes it slow things down considerably if
  # NSIS is in unicode mode
  unicode: false
win:
  certificateSubjectName: Travis Collins
  icon: icon.ico
  target: nsis

# These properties differ between configs
productName: ShieldBattery
productFilename: ShieldBattery
